# TODO: Here be description of the file structure and the process to add variabels to the config 
- magicc7Variable: Surface Air Temperature Change
  gamsVariable: pm_globalMeanTemperature
  fileName: p15_magicc_temp
- magicc7Variable: Effective Radiative Forcing|Anthropogenic
  gamsVariable: p15_forc_magicc
  fileName: p15_forc_magicc
